# Generated by Django 4.2.23 on 2025-07-24 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correspondencecontacts',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='correspondencecontacts',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='correspondencecontacts',
            name='correspondence',
        ),
        migrations.RemoveField(
            model_name='correspondencestatuslog',
            name='from_status',
        ),
        migrations.RemoveField(
            model_name='correspondencestatuslog',
            name='to_status',
        ),
        migrations.AddField(
            model_name='correspondence',
            name='contact',
            field=models.ForeignKey(blank=True, db_column='contact', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.contacts'),
        ),
        migrations.AddField(
            model_name='correspondencestatuslog',
            name='form_status_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='correspondencestatuslog',
            name='to_status_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='correspondence',
            field=models.ForeignKey(db_column='correspondence_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.correspondence'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.CharField(help_text='Path to uploaded file', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_type',
            field=models.CharField(blank=True, help_text='MIME type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assigned_to_id', help_text='Foreign key to Django Auth User model', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='current_status',
            field=models.ForeignKey(blank=True, db_column='current_status_id', help_text='Foreign key to CorrespondenceTypeProcedure; Current status/procedure of this correspondence', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.correspondencetypeprocedure'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='direction',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Internal', 'Internal')], help_text='Incoming, Outgoing, Internal; the flow of the correspondence', max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='parent_correspondence',
            field=models.ForeignKey(blank=True, db_column='parent_correspondence_id', help_text='Self-referencing foreign key for related correspondence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.correspondence'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', help_text='high, normal, low', max_length=10),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type_id', help_text='Foreign key to CorrespondenceTypes', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.correspondencetypes'),
        ),
        migrations.AlterField(
            model_name='correspondencestatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_column='changed_by_id', help_text='Foreign key to Django Auth User model', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة'),
        ),
        migrations.AlterField(
            model_name='correspondencestatuslog',
            name='correspondence',
            field=models.ForeignKey(db_column='correspondence_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.correspondence'),
        ),
        migrations.AlterField(
            model_name='correspondencestatuslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='correspondencetypeprocedure',
            name='correspondence_type',
            field=models.ForeignKey(db_column='correspondence_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='core.correspondencetypes'),
        ),
        migrations.AlterField(
            model_name='correspondencetypes',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Russian', 'Russian')], help_text='General, Russian', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='for soft deletion'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['reference_number', 'correspondence_date'], name='idx_ref_num_date_unique'),
        ),
        migrations.AddIndex(
            model_name='correspondencetypeprocedure',
            index=models.Index(fields=['correspondence_type', 'procedure_name'], name='idx_corr_type_proc_unique'),
        ),
        migrations.DeleteModel(
            name='CorrespondenceContacts',
        ),
    ]
