# Generated by Django 4.2.23 on 2025-07-24 10:57

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_correspondence_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='correspondence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.correspondence'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(help_text='Uploaded file', upload_to=core.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_type',
            field=models.CharField(blank=True, help_text='mime type', max_length=100, null=True),
        ),
    ]
