# Generated by Django 5.1.4 on 2025-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='User department', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name_arabic',
            field=models.CharField(blank=True, help_text='Full name in Arabic', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_session',
            field=models.BooleanField(default=False, help_text='Track if user has an active session'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Last login IP address', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('normal', 'Normal User')], default='normal', help_text='User role for authorization purposes', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
