# Generated by Django 5.1.4 on 2025-07-21 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CorrespondenceTypeProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(help_text='Name of the procedure/status step', max_length=255)),
                ('procedure_order', models.IntegerField(default=0, help_text='Order of this procedure in the workflow')),
                ('is_initial', models.BooleanField(default=False, help_text='True if this is the initial status')),
                ('is_final', models.BooleanField(default=False, help_text='True if this is a final status')),
                ('description', models.TextField(blank=True, help_text='Description of what happens in this procedure', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correspondence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='core.correspondencetypes')),
            ],
            options={
                'verbose_name': 'Correspondence Type Procedure',
                'verbose_name_plural': 'Correspondence Type Procedures',
                'db_table': 'correspondence_type_procedure',
                'ordering': ['correspondence_type', 'procedure_order'],
                'unique_together': {('correspondence_type', 'procedure_name')},
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceStatusLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('change_reason', models.TextField(blank=True, help_text='Optional reason for the status change', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.correspondence')),
                ('from_status', models.ForeignKey(blank=True, help_text='Previous status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_status_logs', to='core.correspondencetypeprocedure')),
                ('to_status', models.ForeignKey(help_text='New status', on_delete=django.db.models.deletion.CASCADE, related_name='to_status_logs', to='core.correspondencetypeprocedure')),
            ],
            options={
                'verbose_name': 'Correspondence Status Log',
                'verbose_name_plural': 'Correspondence Status Logs',
                'db_table': 'correspondence_status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='correspondence',
            name='current_status',
            field=models.ForeignKey(blank=True, help_text='Current status/procedure of this correspondence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.correspondencetypeprocedure'),
        ),
    ]
