# Generated by Django 5.1.4 on 2025-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attachments_correspondence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardphotos',
            name='file_name',
            field=models.CharField(help_text='Original file name', max_length=2048),
        ),
        migrations.AlterField(
            model_name='cardphotos',
            name='file_path',
            field=models.CharField(help_text='Path or URL to the stored image file', max_length=2048),
        ),
    ]
