# Generated by Django 4.2.23 on 2025-07-23 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_correspondence_assigned_to_correspondence_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencestatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة'),
        ),
    ]
