# Generated by Django 5.1.4 on 2025-07-28 14:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cardphotos_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(help_text='Uploaded file', max_length=2048, upload_to=core.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_name',
            field=models.CharField(help_text='Original filename', max_length=1024),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_type',
            field=models.CharField(blank=True, help_text='mime type', max_length=1024, null=True),
        ),
    ]
