# Generated by Django 4.2.23 on 2025-07-23 04:36

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_correspondencestatuslog_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='file_path',
        ),
        migrations.AddField(
            model_name='attachments',
            name='file',
            field=models.FileField(default=None, help_text='Uploaded file', upload_to=core.models.attachment_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachments',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='correspondencestatuslog',
            name='to_status',
            field=models.ForeignKey(help_text='New status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_status_logs', to='core.correspondencetypeprocedure'),
        ),
        migrations.DeleteModel(
            name='CorrespondenceProcedures',
        ),
    ]
