# Generated by Django 4.2.23 on 2025-07-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_attachments_file_path_attachments_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correspondence',
            unique_together={('reference_number', 'correspondence_date')},
        ),
    ]
